using System;
using System.Collections.Generic;

#nullable disable

namespace OrisonSPMSAPI.Models
{
    public partial class Personnel
    {
        public string EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public DateTime? JoiningDate { get; set; }
        public string Status { get; set; }
        public string MaritalStatus { get; set; }
        public string Sex { get; set; }
        public string BankAccountNo { get; set; }
        public string Mobile { get; set; }
        public DateTime? WpExpiryDate { get; set; }
        public DateTime? PassportExpiryDate { get; set; }
        public string LeaveSalary { get; set; }
        public string Ticket { get; set; }
        public string ResidenceAddress { get; set; }
        public string ResidenceAddress1 { get; set; }
        public DateTime? VisaExpiryDate { get; set; }
        public string ResidenceAddress2 { get; set; }
        public string ResidenceAddress3 { get; set; }
        public string ResidencePhoneNo { get; set; }
        public string Branch { get; set; }
        public string Designation { get; set; }
        public string Project { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string SalaryMode { get; set; }
        public string EntryType { get; set; }
        public string Category { get; set; }
        public string VisaDesignation { get; set; }
        public DateTime? IncrementDate { get; set; }
        public string Qualification { get; set; }
        public string QualificationDetails { get; set; }
        public string PermanentAddress { get; set; }
        public string Pbno { get; set; }
        public string Emirate { get; set; }
        public string Email { get; set; }
        public DateTime? Confirmationdate { get; set; }
        public string Wpstatus { get; set; }
        public string PermanentPhoneNo { get; set; }
        public DateTime? ProjectJoinedDate { get; set; }
        public DateTime? LeaveFromDate { get; set; }
        public DateTime? LeaveToDate { get; set; }
        public DateTime? JoinedDateAfterLeave { get; set; }
        public short? LeavePerYear { get; set; }
        public short? LeaveAvailable { get; set; }
        public string OfficialRemarks { get; set; }
        public string PassportRemarks { get; set; }
        public string LabourStatus { get; set; }
        public string VisaRemarks { get; set; }
        public string PersonalRemarks { get; set; }
        public string FinancialRemarks { get; set; }
        public bool Bookmark { get; set; }
        public string VisaType { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public string PlaceOfBirth { get; set; }
        public string Nationality { get; set; }
        public string Religion { get; set; }
        public string PassportNo { get; set; }
        public DateTime? PassportIssueDate { get; set; }
        public string PassportIssuePlace { get; set; }
        public string WpNo { get; set; }
        public DateTime? WpIssueDate { get; set; }
        public string WpIssuePlace { get; set; }
        public string VisaNo { get; set; }
        public DateTime? VisaIssueDate { get; set; }
        public string VisaIssuePlace { get; set; }
        public string BloodGroup { get; set; }
        public string FathersDetails { get; set; }
        public string MothersDetails { get; set; }
        public string WifeHusbandDetails { get; set; }
        public string Child1Details { get; set; }
        public string Child2Details { get; set; }
        public string Child3Details { get; set; }
        public decimal? BasicPay { get; set; }
        public decimal? Accomadation { get; set; }
        public decimal? Transportation { get; set; }
        public decimal? FoodAllowance { get; set; }
        public decimal? Allowance { get; set; }
        public string SerialNo { get; set; }
        public DateTime? LeaveCalculateFrom { get; set; }
        public decimal? Installment { get; set; }
        public decimal? AdvanceBalance { get; set; }
        public decimal? LoanInstallment { get; set; }
        public decimal? LoanBalance { get; set; }
        public string SalaryStatus { get; set; }
        public string BankDetails { get; set; }
        public string ActcoAccountNo { get; set; }
        public short? BranchNo { get; set; }
        public short? EmployeeNo { get; set; }
        public string Grade { get; set; }
        public string Committed { get; set; }
        public string MinistryStatus { get; set; }
        public string Hcno { get; set; }
        public DateTime? HcexpDate { get; set; }
        public DateTime? HcissueDate { get; set; }
        public string HcplaceIssue { get; set; }
        public string DrivingLicenceNo { get; set; }
        public string DrivingLicenceIssuedate { get; set; }
        public string DrivingLicenceIssueplace { get; set; }
        public string DrivingLicenceExpDate { get; set; }
        public string DrivingLicenceType { get; set; }
        public string Mothertongue { get; set; }
        public DateTime? Approveddate { get; set; }
        public string HcountryPhone { get; set; }
        public string EndServiceDetails { get; set; }
        public DateTime? EndServiceDate { get; set; }
        public string PassportStatus { get; set; }
        public string WpStatus1 { get; set; }
        public string ResidenceFileNo { get; set; }
        public string ServiceBenefit { get; set; }
        public string OfficeFileLocation { get; set; }
        public string Hcphone { get; set; }
        public DateTime? ServiceBenefitDate { get; set; }
        public string Lcno { get; set; }
        public DateTime? LcexpDate { get; set; }
        public DateTime? LcissueDate { get; set; }
        public string LcplaceIssue { get; set; }
        public int? OrderNo { get; set; }
        public decimal? MinistrySalary { get; set; }
        public decimal? Gratuity { get; set; }
        public decimal? Incentive { get; set; }
        public decimal? Overtimerate { get; set; }
    }
}
